apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev
  labels:
    name: color-api    
spec:
  containers:
  - name: color-api
    image: shiwani7/color-api-service:1.1.0
    resources:
      requests:
        cpu: '200m'
        memory: '256Mi'
      limits:
        cpu: "500m"
        memory: "512Mi"        
    ports:
      - containerPort: 80