apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  namespace: dev
  labels:
    app: traffic-generator
    tier: backend
spec:
  containers:
  - name: traffic-generator
    image: shiwani7/traffic-gen:1.0.0
    args:
      - 'color-svc.default.svc.cluster.local'
      - '0.5'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"