apiVersion: v1
kind: Pod
metadata:
  name: green-color-api
  labels:
    app: green-color-api
spec:
  containers:
  - name: color-api
    image: shiwani7/color-api-configmap:1.3.0
    env:
      - name: COLOR_CONFIG_PATH
        valueFrom:
          configMapKeyRef:
            key: COLOR_CONFIG_PATH 
            name: green-config
    volumeMounts:
      - name: color-config
        mountPath: /mnt/config
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: color-config
      configMap:
        name: green-config
