apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: alice
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU9NQXdHQTFVRUF3d0ZZV3hwWTJVeERqQU1CZ05WQkFvTUJXRmtiV2x1TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMjV6RUY3SlE4aFZVb2JJUDdQWStzQmpICjdJb2ZJYVlxbFhmWUFZTmUrUk1neU81L1cyKy9ZejFaYitoQTVQeTRKV0hYd3lMMVpRaGFqbTc5Zm43RldHQUsKWDBSMUEyNWt2ZEU4Nzk5WTVhNXJ4RmppNmt2TytEY096RnprU0Fqdk5WbmZNMCt4eWJsdWY1OWxBU3EvbDU3bQp2VXprcWhxdktsRU5MZlJNY2ZwRGFLNE1iVzNCNFBRTVRwUUduaFdFNmFrUVRzWDA5Q2w1WndOMlFqQXF5UFJpCkZTYnF5a2xVRURoYlgzQmhJSFZ1VnFGTy8xT1ZzNmdHVEpuMVU1ZE4vSVRvUEpubmpoci95ZFJEbnErZ05mbWYKWEoxcGpCbHZPeVphTjRYL09iUm9IVXJmNXEzc0ZNMXVPNEtsZGZaU0l1cm9SYStwTnRSVDI3ckQvb0FibVFJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCK2hLd3VmWDR1R1I5cnFaR0NPMzBNdlJmcVdGVHhTCmx3eWRlcWlLVWpnamxNQXpORlZUY0doWDdDSWVSakpaUHBpMytmbG5PZzA0aHR5UXh6YUFUZVhvL3NPT0doUE4KVjBxejBDa1RCVmoxbG0yVHU5TjFjaXdLSnRvMkpEaDgzV2JIK2FOTTlhdmRPNEpLT2h1ZnFpMjFZSVczRFZUbApXSUdwZU5Tck9LWEVpSmY3dEtRMmFJOU05Mnk2VUNFZ0tjL3NzK1dmZ25ITjBFaHRRRUx4cUl1b2xmaVY4YU1vCkx3VXQxZXBhMERBYytPSEtJWXVsOVkyTXNXQ2dyTi8zTW5IbUNoVXVqcXE0TnZWR1dmdWZESElZZitaaTVZZU0KZHdJQ08xeFdOOUR4MGdDeG9zVnJlK2JMLzhWOVpJYTZUMlhmWUJOSHBnU0ZWWVRUazRPa055Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
    - client auth

--- 

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1l6Q0NBVXNDQVFBd0hqRU1NQW9HQTFVRUF3d0RZbTlpTVE0d0RBWURWUVFLREFWaFpHMXBiakNDQVNJdwpEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTBpVlFDN1pZMTB0ZzJjUFdhOU93TWdpNU0rCjNuUU5JSXFvbXFFYURucm45NUFrNEN3VjEzTTFVcEp5UnRhN3dMNEZTTTQ2YTVVN0NpcmJTQk50eUU4d0FpNlgKZmNLVzRSVlRJNlBoTWVETU1tQy9xai9zNjM4dWhMT0t3bWhyZlVjTXo1aU5lcGVRa0h0bmpheUNSUXUvZ21WSApGa3RySHNubUpqSWJkVGxpK2hrVG5Jb3kvYVFRb3NUc3Z1Q3pFdkROK2FJS3A2Um82aEozaHpjS2gxT2xKeUw3ClNiakUweWZPK2NEYkJMVHJsdVNIeDFxNithOTI5Zzc5Y3NqRERrSzNhNnRQeU9zUUJPMkptUklNdEtRN3EzZHYKbERjQ2p0Mld3bzBTTkRFWm1IK2RpK1pGOXBrVWpkV05mNURFTXd0cGhzOXB4L1ZhbElIS0NONnd6ME1DQXdFQQpBYUFBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDR21scDQrTllPL1NTeWtxZHlad2JjTGFwbE9IMTZTU2VVCkUrT3FObkJHbWFJS29zVlpjSGRXWEVGUE5adlVubjhRQmhlWXRoN29PU29GOGdqanYybHM4c1RsaDVJL2JxaHQKMVErdTRmeG9WK2ZKaXF0T09weElhdzExcFZWdWhlOVFjNnY3eVJ5dGNCbVM4d2JONTU4dDU0MlNMRzBOZldDcgpvbTFOVmI4Z0tsU0k1ZkxDM0Npdmg5Wm05TDI4Q3hCSnh1RE5IeUp3aGlKT24rc0lXNFZsSEl3NkFnM0I5Rzd1CmtPMXV2NDRKajI5VHRwbWVnbmwwTjJDZ0pFREt5MjFPNERDYVoreDJQSHlRejZka1Y4M2tPNUlpUWNoZ0ZDK1UKS3F0am1TUitEa2MvNGFndS9vUlFrZTZMQWEwa2ROR0N5ZDFkOHA4WWJXbGlKZjVpZ0k1RQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
    - client auth
