apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    image: shiwani7/color-api-service:1.1.0
    ports:
      - containerPort: 80

---
#we are not mentioning the namespace here so it will be created inside 'default' namespace
apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
  namespace: dev
  labels:
    app: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
  - port: 80
    targetPort: 80

