apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo
  labels:
    name: empty-dir-demo
spec:
  containers:
  - name: empty-dir-demo
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'sleep 3600'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: temporary-storage
        mountPath: /usr/share/temp
  volumes:
  - name: temporary-storage
    emptyDir: {}