apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.36.1
    command:
      - 'sh'
      - '-c'
      - 'echo "$DB_USER" && echo "$DB_PASSWORD" && sleep 1800'
    env:
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: db-creds
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: db-creds
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"